<?php


class DivideByZeroException extends Exception
{
    public function __toString()
    {
        parent::__toString();
        return "Can't divide by zero!"; // TODO: Change the autogenerated stub
    }
}